services: 
  frontend:
    build:
      context: ./marketplace-frontend
      dockerfile: Dockerfile
    depends_on: 
      - backend
    ports:
      - "80:3000"
    networks:
      - app-network

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postuser -d marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    
  backend:  
    image: your-spring-boot-app
    build:
      context: ./marketplace-backend
      dockerfile: dockerFile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:9.2 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/li
    networks:
      - app-network
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  db-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge