services:

  frontend:
    build: 
      context: marketplace-frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
  
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: 