spring.datasource.url=jdbc:postgresql://database:5432/marketplace
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postuser
spring.datasource.password=postpass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update